# Auto-label PRs based on changed files
extension:
  - changed-files:
      - any-glob-to-any-file: 'apps/app-extension/**'

app:
  - changed-files:
      - any-glob-to-any-file: 'apps/app-extension/**'

ui:
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**'

package:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/ui/**'
          - 'packages/shared/**'
          - 'packages/**'

shared:
  - changed-files:
      - any-glob-to-any-file: 'packages/shared/**'

# Label based on file types
typescript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ts'
          - '**/*.tsx'

react:
  - changed-files:
      - any-glob-to-any-file: '**/*.tsx'

test:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.test.tsx'

# Label for documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

# Label for CI/CD changes
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

# Label for dependency changes
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - '**/bun.lock'
