# Auto-label PRs based on changed files
extension:
  - 'apps/app-extension/**'

app:
  - 'apps/app-extension/**'

ui:
  - 'packages/ui/**'

package:
  - 'packages/ui/**'
  - 'packages/shared/**'
  - 'packages/**'

shared:
  - 'packages/shared/**'

# Label based on file types
typescript:
  - '**/*.ts'
  - '**/*.tsx'

react:
  - '**/*.tsx'

test:
  - '**/*.test.ts'
  - '**/*.test.tsx'

# Label for documentation changes
documentation:
  - '**/*.md'

# Label for CI/CD changes
ci:
  - '.github/**'

# Label for dependency changes
dependencies:
  - '**/package.json'
  - '**/bun.lock'
