import {
  ArrowDown01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  BluetoothIcon,
  Cancel01Icon,
  CodeIcon,
  ComputerIcon,
  CreditCardIcon,
  DownloadIcon,
  EyeIcon,
  File01Icon,
  FileIcon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  HelpCircleIcon,
  KeyboardIcon,
  LanguageCircleIcon,
  LayoutIcon,
  LogoutIcon,
  MailIcon,
  MoonIcon,
  MoreHorizontalCircle01Icon,
  MoreVerticalCircle01Icon,
  NotificationIcon,
  PaintBoardIcon,
  PlusSignIcon,
  SearchIcon,
  SettingsIcon,
  ShieldIcon,
  SunIcon,
  Tick02Icon,
  UnfoldMoreIcon,
  UserIcon,
} from "@hugeicons/core-free-icons";

export const iconRegistry = {
  "arrow-down": ArrowDown01Icon,
  "arrow-right": ArrowRight01Icon,
  "arrow-up": ArrowUp01Icon,
  bluetooth: BluetoothIcon,
  cancel: Cancel01Icon,
  code: CodeIcon,
  computer: ComputerIcon,
  "credit-card": CreditCardIcon,
  download: DownloadIcon,
  eye: EyeIcon,
  file: FileIcon,
  "file-01": File01Icon,
  "floppy-disk": FloppyDiskIcon,
  folder: FolderIcon,
  "folder-open": FolderOpenIcon,
  "help-circle": HelpCircleIcon,
  keyboard: KeyboardIcon,
  "language-circle": LanguageCircleIcon,
  layout: LayoutIcon,
  logout: LogoutIcon,
  mail: MailIcon,
  moon: MoonIcon,
  "more-horizontal": MoreHorizontalCircle01Icon,
  "more-vertical": MoreVerticalCircle01Icon,
  notification: NotificationIcon,
  "paint-board": PaintBoardIcon,
  plus: PlusSignIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  shield: ShieldIcon,
  sun: SunIcon,
  tick: Tick02Icon,
  "unfold-more": UnfoldMoreIcon,
  user: UserIcon,
} as const;

export type IconName = keyof typeof iconRegistry;
